# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 1000
      min-spare: 30
    connection-timeout: 5000ms
  port: 8080
  servlet:
    context-path: /api

spring:
  # Environment dev|test|prod
  profiles:
    active: dev
  # Jackson time format
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true

  mvc:
    throw-exception-if-no-handler-found: true
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
#  resources:
#    add-mappings: false


#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #Entity scan, multiple packages are separated by commas or semicolons
  typeAliasesPackage: io.renren.modules.*.entity
  global-config:
    #Database related configuration
    db-config:
      #Primary key type AUTO: "Database ID auto-increment", INPUT: "User input ID", ID_WORKER: "Global unique ID (digital type unique ID)", UUID: "Global unique ID UUID";
      id-type: AUTO
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  #Native configuration
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'


renren:
  redis:
    open: false
  shiro:
    redis: false

  jwt:
    # Encryption Key
    secret: f4e2e52034348f86b67cde581c0f9eb5

    expire: 604800
    header: token